- doc: Test outline for Segmentation_Values_Testing
  job:
    Image to segment:
      class: File
      path: test-data/Image to segment.tiff
      filetype: tiff
    Sigma Values:
      class: File
      path: test-data/Sigma Values.tabular
      filetype: tabular
    Ground Truth Image:
      class: File
      path: test-data/Ground Truth Image.tiff
      filetype: tiff
  outputs:
    out_file1:
      path: test-data/out_file1.tabular
